#! /bin/sh

### BEGIN INIT INFO
# Provides:		leds
# Default-Start:	2 3 4 5
# Default-Stop:
# Required-Start:	$network $local_fs
# Required-Stop:	$network $local_fs
# Short-Description:	Fadecandy LED server
### END INIT INFO

set -e
umask 022

. /lib/lsb/init-functions

EXECUTE="/home/averdow/pulse/patterns/raver_plaid.py"


case "$1" in
  start)
	log_daemon_msg "Starting OPC data stream" "leds" || true
	if start-stop-daemon --start --quiet --oknodo --background --exec $EXECUTE; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
  stop)
	log_daemon_msg "Stopping OPC data stream" "leds" || true
	if start-stop-daemon --stop --quiet --oknodo --exec $EXECUTE; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  status)
	status_of_proc $EXECUTE leds && exit 0 || exit $?
	;;

  *)
	log_action_msg "Usage: /etc/init.d/leds {start|stop|status}" || true
	exit 1
esac

exit 0
